package com.example.mvp.myapplication.greedao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.mvp.myapplication.greedao.ItemDaoBean;
import com.example.mvp.myapplication.greedao.PhoneDaoBean;
import com.example.mvp.myapplication.greedao.SearchDaoBean;

import com.example.mvp.myapplication.greedao.ItemDaoBeanDao;
import com.example.mvp.myapplication.greedao.PhoneDaoBeanDao;
import com.example.mvp.myapplication.greedao.SearchDaoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig itemDaoBeanDaoConfig;
    private final DaoConfig phoneDaoBeanDaoConfig;
    private final DaoConfig searchDaoBeanDaoConfig;

    private final ItemDaoBeanDao itemDaoBeanDao;
    private final PhoneDaoBeanDao phoneDaoBeanDao;
    private final SearchDaoBeanDao searchDaoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        itemDaoBeanDaoConfig = daoConfigMap.get(ItemDaoBeanDao.class).clone();
        itemDaoBeanDaoConfig.initIdentityScope(type);

        phoneDaoBeanDaoConfig = daoConfigMap.get(PhoneDaoBeanDao.class).clone();
        phoneDaoBeanDaoConfig.initIdentityScope(type);

        searchDaoBeanDaoConfig = daoConfigMap.get(SearchDaoBeanDao.class).clone();
        searchDaoBeanDaoConfig.initIdentityScope(type);

        itemDaoBeanDao = new ItemDaoBeanDao(itemDaoBeanDaoConfig, this);
        phoneDaoBeanDao = new PhoneDaoBeanDao(phoneDaoBeanDaoConfig, this);
        searchDaoBeanDao = new SearchDaoBeanDao(searchDaoBeanDaoConfig, this);

        registerDao(ItemDaoBean.class, itemDaoBeanDao);
        registerDao(PhoneDaoBean.class, phoneDaoBeanDao);
        registerDao(SearchDaoBean.class, searchDaoBeanDao);
    }
    
    public void clear() {
        itemDaoBeanDaoConfig.clearIdentityScope();
        phoneDaoBeanDaoConfig.clearIdentityScope();
        searchDaoBeanDaoConfig.clearIdentityScope();
    }

    public ItemDaoBeanDao getItemDaoBeanDao() {
        return itemDaoBeanDao;
    }

    public PhoneDaoBeanDao getPhoneDaoBeanDao() {
        return phoneDaoBeanDao;
    }

    public SearchDaoBeanDao getSearchDaoBeanDao() {
        return searchDaoBeanDao;
    }

}
